  apiVersion: v1
  kind: Service
  metadata:
    name: hello-python-service
  spec:
    selector:
      app: hello-python
    ports:
      - name: http
        protocol: TCP
        port: 5000
        targetPort: 5000
    type: LoadBalancer